# Generated by Django 3.2.6 on 2021-12-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('est_date', models.DateField()),
                ('hod', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(default=25)),
                ('place', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empdept.departments')),
            ],
        ),
    ]
